version: 2
jobs:

  test_backend:
    docker:
      - image: circleci/python:3.7
      - image: circleci/mongo:4.0-ram
    working_directory: ~/src
    steps:
      - checkout
      - run: python3 -m venv ~/venv
      - run: ~/venv/bin/pip install -U pip wheel
      - run: ~/venv/bin/pip install -r backend/requirements.txt
      - run: ~/venv/bin/pip install -r backend/requirements-tests.txt
      - run: ~/venv/bin/pip install -e backend
      - run: echo ~/venv/bin/py.test -v --tb=native backend/tests

  build_docker_image_frontend:
    docker:
      - image: docker:stable
    working_directory: /src
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
          - v2-frontend
      - run: gunzip /docker_image_cw_frontend.tar.gz || true
      - run: docker load -i /docker_image_cw_frontend.tar || true
      - run: docker images
      - run: cd frontend && docker build -t cw_frontend --pull --cache-from cw_frontend .
      - run: docker save -o /docker_image_cw_frontend.tar cw_frontend
      - run: gzip -k3 /docker_image_cw_frontend.tar
      - save_cache:
          key: v2-frontend-{{ .Branch }}-{{ epoch }}
          paths:
          - /docker_image_cw_frontend.tar.gz
      - run: docker images
      #- store_artifacts:
      #    path: /docker_image_cw_frontend.tar.gz
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              set -ex
              apk add openssh rsync
              echo '207.154.235.213 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMd2qF3m1mtvgxq45xX8F+po9GLeGFgqXp051IsZZKKi' >> ~/.ssh/known_hosts
              rsync -vz --progress /docker_image_cw_frontend.tar circleci@207.154.235.213:
            fi

  build_docker_image_backend:
    docker:
      - image: docker:stable
    working_directory: /src
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
          - v2-backend
      - run: gunzip /docker_image_cw_backend.tar.gz || true
      - run: docker load -i /docker_image_cw_backend.tar || true
      - run: cd backend && docker build -t cw_backend --pull --cache-from cw_backend .
      - run: docker save -o /docker_image_cw_backend.tar cw_backend
      - run: gzip -k3 /docker_image_cw_backend.tar
      - save_cache:
          key: v2-backend-{{ .Branch }}-{{ epoch }}
          paths:
          - /docker_image_cw_backend.tar.gz
      - run: docker images
      #- store_artifacts:
      #    path: /docker_image_cw_backend.tar.gz
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              set -ex
              apk add openssh rsync
              echo '207.154.235.213 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMd2qF3m1mtvgxq45xX8F+po9GLeGFgqXp051IsZZKKi' >> ~/.ssh/known_hosts
              rsync -vz --progress /docker_image_cw_backend.tar circleci@207.154.235.213:
            fi

  call_deploy_script:
    docker:
      - image: circleci/python:3.6
    steps:
      - run: mkdir -p ~/.ssh
      - run:
          name: setup SSH server key fingerprint
          command: |
            echo '207.154.235.213 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMd2qF3m1mtvgxq45xX8F+po9GLeGFgqXp051IsZZKKi' >> ~/.ssh/known_hosts
      - deploy:
          command: |
            ssh circleci@207.154.235.213 sudo /root/pyladies-courseware/deployment/ci_deploy.sh

  build_and_deploy_demo:
    docker:
      - image: docker:stable
    working_directory: /src
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
          - v3-demo
      - run: gunzip /docker_image_cw.tar.gz || true
      - run: docker load -i /docker_image_cw.tar || true
      - run: docker images
      - run: docker images -a
      - run: docker build -t cw --pull --cache-from cw .
      - run: docker save -o /docker_image_cw.tar cw
      - run: gzip -k3 /docker_image_cw.tar
      - save_cache:
          key: v3-demo-{{ .Branch }}-{{ epoch }}
          paths:
          - /docker_image_cw.tar.gz
      - run: docker images
      - run: docker images -a
      - run:
          name: setup SSH server key fingerprint
          command: |
            echo '207.154.235.213 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMd2qF3m1mtvgxq45xX8F+po9GLeGFgqXp051IsZZKKi' >> ~/.ssh/known_hosts
      - run: apk add openssh rsync
      - run: 'rsync -vz --progress /docker_image_cw.tar circleci@207.154.235.213:'
      - run: ssh circleci@207.154.235.213 sudo /root/pyladies-courseware/deployment/ci_deploy_demo.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_backend
      - build_docker_image_frontend
      - build_docker_image_backend
      - call_deploy_script:
          requires:
            - test_backend
            - build_docker_image_frontend
            - build_docker_image_backend
          filters:
            branches:
              only: master
      - build_and_deploy_demo:
          requires:
            - test_backend
          filters:
            branches:
              only: master
